resolver: lts-15.00

packages:
- .

extra-deps:
- aeson-quick-0.1.3@sha256:19e63adcbeaae88f0bfa8006e4d63e8981254f57587580b9eb949e63700375e4,2061
- git: https://github.com/ssadler/haskoin-core
  commit: 1efb7a5764cf6846122d2be73c306e3d826db085
- git: https://github.com/haskoin/secp256k1-haskell
  commit: ff13d39de623e0349143af5514fce1532c84cdae
- msgpack-1.0.1.0@sha256:a87b663fc28d661b41552331d22e10b34028cad8a592ae758ac47e363933b6bd,3004

flags:
  secp256k1-haskell:
    recovery: true


# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.1"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
